name: prod-slack-altinn - Auto deploy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ release ]
    paths:
    - '**'
    - '.github/workflows/prod-slack-altinn-AutoDeployTrigger-06da9e65-21d6-4cd0-803b-5776683d6cfc.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod-slack-altinn

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.DIGDIRASSISTANTSALTINN_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: altinnaicontainers.azurecr.io
          registryUsername: ${{ secrets.DIGDIRASSISTANTSALTINN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DIGDIRASSISTANTSALTINN_REGISTRY_PASSWORD }}
          containerAppName: digdir-assistants-altinn
          resourceGroup: altinn-ai-assistant
          imageToBuild: altinnaicontainers.azurecr.io/digdir-assistants-prod:${{ github.sha }}
          environmentVariables: VITE_SLACK_APP_SUPABASE_API_URL=${{env.VITE_SLACK_APP_SUPABASE_API_URL}} VITE_SLACK_APP_SUPABASE_ANON_KEY=${{env.VITE_SLACK_APP_SUPABASE_ANON_KEY}}
          
            

     

