name: test-slack-kudos - Auto deploy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature/import-kudos-docs ]
    paths:
    - '**'
    - '.github/workflows/test-slack-kudos-*.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: test-slack-kudos

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.TESTSLACKKUDOS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          acrName: altinnaicontainers
          resourceGroup: altinn-ai-assistant
          containerAppName: test-slack-kudos
          containerAppEnvironment: managedEnvironment-altinnaiassista-a61b
          location: norwayeast
          imageToBuild: altinnaicontainers.azurecr.io/assistants-slack-test:${{ github.sha }}
          buildArguments: |
            "VITE_SLACK_APP_SUPABASE_API_URL=${{ vars.SLACK_APP_SUPABASE_API_URL }}"
            "VITE_SLACK_APP_SUPABASE_ANON_KEY=${{secrets.SLACK_APP_SUPABASE_ANON_KEY}}"
          environmentVariables: >
            "OPENAI_API_KEY=secretref:openai-api-key" 
            "AZURE_OPENAI_API_KEY=secretref:azure-openai-api-key" 
            "SLACK_APP_TOKEN=secretref:slack-app-token" 
            "SLACK_BOT_TOKEN=secretref:slack-bot-token" 
            "SLACK_BOT_SIGNING_SECRET=secretref:slack-bot-signing-secret" 
            "TYPESENSE_API_KEY=secretref:typesense-api-key" 
            "SLACK_APP_SUPABASE_API_URL=${{ vars.SLACK_APP_SUPABASE_API_URL }}" 
            "SLACK_APP_SUPABASE_ANON_KEY=${{ secrets.SLACK_APP_SUPABASE_ANON_KEY }}"
            "USE_AZURE_OPENAI_API=${{ vars.USE_AZURE_OPENAI_API}}"
            "OPENAI_API_URL=${{ vars.OPENAI_API_URL }}"
            "OPENAI_API_MODEL_NAME=${{ vars.OPENAI_API_MODEL_NAME }}"
            "AZURE_OPENAI_API_URL=${{ vars.AZURE_OPENAI_API_URL }}"
            "AZURE_OPENAI_DEPLOYMENT=${{ vars.AZURE_OPENAI_DEPLOYMENT }}"
            "AZURE_OPENAI_VERSION=${{ vars.AZURE_OPENAI_VERSION }}"
            "COLBERT_API_URL=${{ vars.COLBERT_API_URL }}"
            "TYPESENSE_API_HOST=${{ vars.TYPESENSE_API_HOST }}"
            "DEBUG_SLACK=${{ vars.DEBUG_SLACK }}"
            "DEBUG_INSTRUCTOR=${{ vars.DEBUG_INSTRUCTOR }}"
            "LOG_LEVEL=${{ vars.LOG_LEVEL }}"

                      
          
               
          
          