name: Trigger auto deployment for test-infoportal-assistant

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test-infoportal-assistant-AutoDeployTrigger-358a9075-bef2-4d67-83aa-f31b197c1875.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTINFOPORTALASSISTANT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTINFOPORTALASSISTANT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTINFOPORTALASSISTANT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: altinnaicontainers.azurecr.io
          registryUsername: ${{ secrets.TESTINFOPORTALASSISTANT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTINFOPORTALASSISTANT_REGISTRY_PASSWORD }}
          containerAppName: test-infoportal-assistant
          resourceGroup: assistants-prod-norwayeast
          imageToBuild: altinnaicontainers.azurecr.io/test-infoportal-assistant:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


